PREFIX omoschema: <http://purl.obolibrary.org/obo/schema/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX RO: <http://purl.obolibrary.org/obo/RO_>
PREFIX OMO: <http://purl.obolibrary.org/obo/OMO_>
PREFIX IAO: <http://purl.obolibrary.org/obo/IAO_>
PREFIX OBI: <http://purl.obolibrary.org/obo/OBI_>
PREFIX NCIT: <http://purl.obolibrary.org/obo/NCIT_>
PREFIX oio: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX linkml: <https://w3id.org/linkml/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX sdo: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pav: <http://purl.org/pav/>
PREFIX prov: <http://www.w3.org/ns/prov-o#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX shex: <http://www.w3.org/ns/shex#>

SELECT
  ?check
  ?graph
  ?subject
  ?predicate
  ?object
WHERE {
 GRAPH ?graph {
  ?subject rdf:type owl:AnnotationProperty ;
     ?predicate ?object .
  FILTER NOT EXISTS {
    ?object rdf:type ?otype .
    FILTER ( ?otype IN (
      linkml:Any
      
      ))
  }
 }
 VALUES ?check { linkml:range }
 VALUES ?predicate { IAO:0100001  }
 
}  



